language: node_js
node_js:
  - node
addons:
  code_climate:
    repo_token:
      secure: QZgeGsv9vMUWR/Mvs2DiAx9/CxY3fzwA3S7rW8WybmyLIEYpkkCj7JoKxaSIltQSmpGQ0BtKZR77gfVV59tq0hVJesXsLKy9a7VLLR+1ie9CVOsEurtWlIWHX3/uKppJceoEndpmxa/OAmV2hYr/OOiwt6RFkMReC7dCzkUd6+kytqyRTNMa/3zd6hk/QA8lqgGMnc0bEck4s/vqNsjos5ET2OwYfNdw2krPjN2XCJ00yV3TShRZm/Y/OrVAIaHvUu4tDj5sGkCph+Typr1fuABxfCKmKKCWx+HXEs3dYFtNCQuniI+0MqzvreZDCj3rOHytBppeTvIBtHmF3ormUb/e3UdPaQ+9O8kJKycMuAzN6YsMBcLxjPY5xMxzeEpo7+UXDxJgT8gl3j5YINMm4pDPqtJyfgQu4FZSRpRBi76sHjzmoCbv9y9P5JQhy1JNN/MZBjAkGu3nZ3i0agdvOe2iMtA3gEUNICL4PL6BBKIM48S9zsk9F7qfdySHvslXB5ltesm+nNAgLrd38xWb7DdYZ6vZeMkC2Rp7lQJnv7Rg36B7Rn++BtINYlkt/MBVnaoXydE5khFDflmBNwkfDhzsyukaINtu4i7KJeq3EhKbYk9gKm6yMZV/xk+TJI7vv77vBf2M1GDb5bp9MPqZvcclGgX3Y4KsEcINdidd6eI=
cache: yarn
env:
  matrix:
    - TEST_SUITE=client
    - TEST_SUITE=server
before_script:
  # - yarn install
  # codeclimate setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  # - ./cc-test-reporter before-build
script:
  - yarn lint:$TEST_SUITE
  - yarn test:coverage:$TEST_SUITE
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.$TEST_SUITE.json $TEST_SUITE/coverage/lcov.info
after_success:
  # - ./cc-test-reporter after-build -t lcov -p ./ --exit-code $TRAVIS_TEST_RESULT
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2 -o coverage/codeclimate.total.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage -i coverage/codeclimate.total.json; fi
