language: node_js
node_js:
- node
addons:
  code_climate:
    repo_token:
      secure: "YTkkpOLk+6R0kGaIN+sZgOMll2wagwjA5cjYOlaew5SARfnq4W1HYtFEJKaW/XxV9IljNEwX12Aalj6S94FxjGiSA6Nzbvz/vuSOaOVtuRRzH805xjNv3fEuNPTiuzSgDzhU3Tm6T2lZ3lOV9r/vtqlBu5dR3F3w5tX/ZGsidcdawOPSJxx2Ed96GIvYGOmx02hf92GhG5GROKYknwIW3CnNhGTmNGWPCy4F1gjAzxdeqLf3RrdQxiy0LeCUXvaUMxWb8I6rqJuje1AwsFKbxPrxI8Hk9zwcDEd3KBJoGMIWHJf2plfeepaB7kjyy2hjeAnOmoeKhF1qEvOsqT6VIeD7LUgp7iN/GKr53QuSrK+TB2k0KBmEO/UJTHam/AVG2W08XgyxyA4fI7GSf016uck/p14NT+isc812wvUVr1KOqp2U6FVSxx2RwtD0Yqpai0jNVRhb3d6xqBgJEwtc2JxmOWjZ6Jdq+m5lYoh3+CLSvyTJyVJRSFaVRVfDk00/NwYHVA+jeWc+F54s/wMyJMofD87YikfkpPaLXYdhu6HECb2drfbVWcecOWiASD9XFGO5eB2ssdvE6CkXEZzzIWcThPDjZg7giCeEa9SbdhQqaQsUWE1wrE4326LnDva2nF23Az4axJvk1ilPl8ZJ648GWXPtU0xKdN97fD7UTQY="cache:
- yarn: true
  directories:
  - $HOME/google-cloud-sdk
env:
  global:
  # disable google cloud sdk prompts
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  matrix:
  - TEST_SUITE=client
  - TEST_SUITE=server
before_install:
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
# This line is critical. We setup the SDK to take precedence in our environment over the old SDK that is already on the machine.
- source $HOME/google-cloud-sdk/path.bash.inc
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_4912ff11cfe7_key -iv $encrypted_4912ff11cfe7_iv -in client-secret.json.enc -out client-secret.json -d
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file client-secret.json
# install codeclimate reporter
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- yarn lint:$TEST_SUITE
- yarn test:coverage:$TEST_SUITE
after_success:
- "./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.$TEST_SUITE.json $TEST_SUITE/coverage/lcov.info"
- gsutil cp -r coverage/ gs://racer01-openhams.appspot.com/
# deploy:
#   provider: gcs
#   access_key_id: GOOGFVHSBSXTKOUI2OXMMMBY
#   secret_access_key: $GCS_SECRET
#   bucket: racer01-openhams.appspot.com
#   skip_cleanup: true
#   upload-dir: $TEST_SUITE
#   local-dir: coverage
#   on:
#     repo: openHAMS/openHAMS-web2
jobs:
  include:
  - stage: Codeclimate
    env:
    - TEST_SUITE=codeclimate
    before_install:
    - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
        rm -rf $HOME/google-cloud-sdk;
        curl https://sdk.cloud.google.com | bash > /dev/null;
      fi
    # This line is critical. We setup the SDK to take precedence in our environment over the old SDK that is already on the machine.
    - source $HOME/google-cloud-sdk/path.bash.inc
    # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
    - openssl aes-256-cbc -K $encrypted_4912ff11cfe7_key -iv $encrypted_4912ff11cfe7_iv -in client-secret.json.enc -out client-secret.json -d
    # Here we use the decrypted service account credentials to authenticate the command line tool
    - gcloud auth activate-service-account --key-file client-secret.json
    # install codeclimate reporter
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    before_script:
    - gsutil cp -r gs://racer01-openhams.appspot.com/coverage/ /
    script:
    - ls coverage/
    - "./cc-test-reporter -d sum-coverage coverage/codeclimate.*.json -p 2 -o coverage/codeclimate.total.json"
    - "./cc-test-reporter upload-coverage -i coverage/codeclimate.total.json"
